version: "3"

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes :
      - ./default_conf/nginx.conf:/etc/nginx/nginx.conf
      - ./sites-available:/etc/nginx/sites-available
      - ./sites-enabled:/etc/nginx/sites-enabled
      - ./html:/var/www/html
      - ./log:/var/log/nginx
#    command: sh -c "rm /etc/nginx/nginx.conf"
    ports:
      - 80:80
      - 433:433
